package enums;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static enums.UnoRuleCategory.*;

public enum UnoRule {
    TWO_PLAYERS(NUMBER_OF_PLAYERS,"2"),
    THREE_PLAYERS(NUMBER_OF_PLAYERS,"3"),
    FOUR_PLAYERS(NUMBER_OF_PLAYERS,"4"),
    FIVE_PLAYERS(NUMBER_OF_PLAYERS,"5"),
    SIX_PLAYERS(NUMBER_OF_PLAYERS,"6"),
    SEVEN_PLAYERS(NUMBER_OF_PLAYERS,"7"),
    EIGHT_PLAYERS(NUMBER_OF_PLAYERS,"8"),
    NINE_PLAYERS(NUMBER_OF_PLAYERS,"9"),
    TEN_PLAYERS(NUMBER_OF_PLAYERS,"10"),

    ONE_ZERO_EIGHT_CARDS(NUMBER_OF_CARDS,"108"),
    TWO_ONE_SIX_CARDS(NUMBER_OF_CARDS,"216"),

    SEVEN_CARDS_DEALT(CARDS_DEALT,"7"),
    FOURTEEN_CARDS_DEALT(CARDS_DEALT,"14"),
    TWENTY_CARDS_DEALT(CARDS_DEALT,"20"),

    LTR_PLAYING_FLOW(PLAYING_FLOW,"LTR"),
    RTL_PLAYING_FLOW(PLAYING_FLOW,"LTR"),
    FROM_MIDDLE_TR_FLOW(PLAYING_FLOW,"MTR"),
    FROM_MIDDLE_TL_FLOW(PLAYING_FLOW,"MTL"),

    SAY_UNO_ON_LAST_TWO_CARDS(SAYING_UNO,"SAY_UNO_ON_LAST_TWO_CARDS"),
    SAY_UNO_ON_LAST_CARD(SAYING_UNO,"SAY_UNO_ON_LAST_CARD"),

    CONTINUE_IF_YOU_HAVE(CONTINUE_IF_HAVING,"CONTINUE_IF_YOU_HAVE"),
    CONTINUE_IF_YOU_HAVE_COUNT_2(CONTINUE_IF_HAVING,"CONTINUE_IF_YOU_HAVE_COUNT_2"),

    DRAW_ONE_CARD_IF_YOU_DONT_HAVE(DRAW_CARDS,"1"),
    DRAW_TWO_CARDS_IF_YOU_DONT_HAVE(DRAW_CARDS,"2"),

    DUPLICATED_DRAW_CARDS_ARE_GATHERED(DRAW_CARDS_IS_GATHERED,"DUPLICATED_DRAW_CARDS_ARE_GATHERED"),
    NO_GATHERING_FOR_DRAW_CARDS(DRAW_CARDS_IS_GATHERED,"NO_GATHERING_FOR_DRAW_CARDS"),

    PLAY_AFTER_DRAWING(PLAY_IF_DRAWN,"PLAY_AFTER_DRAWING"),
    IF_DRAW_THAN_DONT_PLAY(PLAY_IF_DRAWN,"IF_DRAW_THAN_DONT_PLAY"),

    SAME_NUMBER_DIFFERENT_COLOR_ALLOWED(COLOR_RESTRICTION,"SAME_NUMBER_DIFFERENT_COLOR_ALLOWED"),
    ONLY_SAME_COLOR_IS_ALLOWED(COLOR_RESTRICTION,"ONLY_SAME_COLOR_IS_ALLOWED"),

    LOSER_MUST_BE_PUNISHED(PUNISHMENTS,"LOSER_MUST_BE_PUNISHED"),
    NO_PUNISHMENTS(PUNISHMENTS,"NO_PUNISHMENTS"),

    WITH_POINTS(POINTS,"WITH_POINTS"),
    LAST_ONE_IS_WINNER(POINTS,"LAST_ONE_IS_WINNER");

    private final UnoRuleCategory category;
    private final String value;

    UnoRule(UnoRuleCategory category, String value) {
        this.category = category;
        this.value = value;
    }

    public UnoRuleCategory getCategory() {
        return category;
    }
    public String getValue() {
        return value;
    }



    public static Set<UnoRule> getBasicUnoRules() {
        Set<UnoRule> basicUnoRules = new HashSet<>();
         basicUnoRules.add(TWO_PLAYERS);
         basicUnoRules.add(ONE_ZERO_EIGHT_CARDS);
         basicUnoRules.add(SEVEN_CARDS_DEALT);
         basicUnoRules.add(LTR_PLAYING_FLOW);
         basicUnoRules.add(SAY_UNO_ON_LAST_TWO_CARDS);
         basicUnoRules.add(CONTINUE_IF_YOU_HAVE);
         basicUnoRules.add(DRAW_ONE_CARD_IF_YOU_DONT_HAVE);
         basicUnoRules.add(DUPLICATED_DRAW_CARDS_ARE_GATHERED);
         basicUnoRules.add(PLAY_AFTER_DRAWING);
         basicUnoRules.add(SAME_NUMBER_DIFFERENT_COLOR_ALLOWED);
         basicUnoRules.add(LOSER_MUST_BE_PUNISHED);
         basicUnoRules.add(WITH_POINTS);
        return basicUnoRules;
    }




}
